<%@ Page Title="Listado" Language="C#" MasterPageFile="~/Site/MantTemplate.Master" AutoEventWireup="true" CodeBehind="ListaArtist.aspx.cs" Inherits="WebForms.Test.Site.ArtistWeb.ListaArtist" %>

<asp:Content ID="ButtonContent" ContentPlaceHolderID="ButtonContent" runat="server">
    <a class="btn btn-info" href="CrearArtist.aspx">
        <span class="glyphicon glyphicon-plus"></span>Crear Artista
    </a>
    <div>
        Buscar artista:
        <asp:TextBox ID="txtnombre" runat="server"></asp:TextBox>
        <asp:Button ID="btnbuscar" runat="server" Text="Buscar" OnClick="btnbuscar_Click"/>
    </div>
</asp:Content>

<asp:Content ID="ListContent" ContentPlaceHolderID="ArtistContent" runat="server">
    <div class="row">
        <h3>Listado de artistas</h3>
    </div>
    <asp:SqlDataSource
        ID="SqlDataSource"
        runat="server"
        ConnectionString="<%$ConnectionStrings:ChinookcnxEF%>"
        SelectCommand="GetListaArtista"
        SelectCommandType="StoredProcedure"
        DeleteCommand="DeleteArtist"
        DeleteCommandType="StoredProcedure">
        <DeleteParameters>
            <asp:Parameter Name="ArtistId" Type="Int32" />
        </DeleteParameters>
    </asp:SqlDataSource>

    <div class="row">
        <br />
        <asp:GridView ID="ArtistGridView" 
            CssClass="table table-striped table-bordered"
            runat="server"
            AllowPaging="true"
            PageSize="12"
            AllowSorting="true"
            AutoGenerateColumns="true"
          
            AutoGenerateDeleteButton="true"
            DataKeyNames="Artistid"
            AutoGenerateEditButton="true"
            OnPageIndexChanging="ArtistGridView_PageIndexChanging"
            >
            <PagerSettings Mode="NumericFirstLast" Position="TopAndBottom" />
        </asp:GridView>
        <br />
    </div>
    <div>
        <asp:Label ID="lblpagina" runat="server" Text=""></asp:Label>
    </div>
    <div>
        <asp:Button ID="btnfirst" runat="server" Text="Primer Registro" OnClick="btnfirst_Click" />
        <asp:Button ID="btnnext" runat="server" Text="Siguiente Registro" OnClick="btnnext_Click" />
        <asp:Button ID="btnprev" runat="server" Text="Registro Anterior" OnClick="btnprev_Click" />
        <asp:Button ID="btnlast" runat="server" Text="Ultimo Registro" OnClick="btnlast_Click" />
    </div>    
</asp:Content>
